// Generated by CoffeeScript 1.8.0
var Cell;

Cell = (function() {
  function Cell(row, column, nbColor) {
    this.row = row;
    this.column = column;
    this.state = null;
    this.prevState = null;
    this.neighbours = Array();
  }

  Cell.prototype.display = function() {
    $("#cell" + this.row + "x" + this.column).attr("color", this.state);
  };

  Cell.prototype.initialize = function(state) {
    this.state = state;
    this.prevState = state;
    display();
  };

  Cell.prototype.addNeighbour = function(cell) {
    this.neighbours.push(cell);
  };

  Cell.prototype.notify = function(color) {
    var i, _i, _len, _ref;
    this.prevState = this.state;
    this.state = color;
    display();
    _ref = this.neighbours.length;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      this.neighbours[i].notify(this.state(this.prevState));
    }
  };

  Cell.prototype.notify = function(current, previous) {
    var i, _i, _len, _ref;
    if (this.state === previous && this.state === !current) {
      this.prevState = state;
      this.state = current;
      display();
      _ref = this.neighbours.length;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        this.neighbours[i].notify(this.state, this.prevState);
      }
    }
  };

  return Cell;

})();

//# sourceMappingURL=cell.js.map
