// Generated by CoffeeScript 1.8.0
var Cell;

Cell = (function() {
  function Cell(row, column, nbColor) {
    this.row = row;
    this.column = column;
    this.neighbours = Array();
    this.state = Math.floor(Math.random() * nbColor);
    this.prevState = this.state;
  }

  Cell.prototype.display = function() {
    $("#cell" + this.row + "x" + this.column).attr("state", this.state);
  };

  Cell.prototype.addNeighbour = function(cell) {
    this.neighbours.push(cell);
  };

  Cell.prototype.change = function(color) {
    var i, _i, _ref;
    this.prevState = this.state;
    this.state = color;
    this.display();
    for (i = _i = 0, _ref = this.neighbours.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      this.neighbours[i].notify(this.state, this.prevState);
    }
  };

  Cell.prototype.notify = function(current, previous) {
    var i, _i, _ref;
    current = parseInt(current);
    previous = parseInt(previous);
    if (this.state === previous && this.state !== current) {
      this.prevState = this.state;
      this.state = current;
      this.display();
      for (i = _i = 0, _ref = this.neighbours.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        this.neighbours[i].notify(this.state, this.prevState);
      }
    }
  };

  return Cell;

})();

//# sourceMappingURL=cell.js.map
