// Generated by CoffeeScript 1.8.0
var Grid;

Grid = (function() {
  function Grid(size, nbColor) {
    var column, i, row, _i, _j, _ref, _ref1;
    this.grid = Array();
    $("#board").empty();
    for (i = _i = 0, _ref = size * size - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      row = Math.floor(i / size);
      column = i % size;
      $("#game").css("width", size * 60 + 60);
      $("#game").css("height", size * 60 + 60);
      $("#board").css("width", size * 60);
      $("#board").css("height", size * 60);
      $("#board").append("<div class='cell' id='cell" + row + "x" + column + "'></div>");
      this.grid.push(new Cell(row, column, nbColor));
    }
    for (i = _j = 0, _ref1 = size * size - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
      if (i > size) {
        this.grid[i].addNeighbour(this.grid[i - size]);
      }
      if (i % size > 0) {
        this.grid[i].addNeighbour(this.grid[i - 1]);
      }
      if ((i % size) < (size - 1)) {
        this.grid[i].addNeighbour(this.grid[i + 1]);
      }
      if (i < (size * (size - 1))) {
        this.grid[i].addNeighbour(this.grid[i + size]);
      }
    }
  }

  Grid.prototype.change = function(color) {
    return this.grid[0].notify(color);
  };

  return Grid;

})();

//# sourceMappingURL=grid.js.map
